# Generated by Django 4.1.5 on 2023-02-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('last_Name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('Email_ID', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('re_enter_password', models.CharField(max_length=100)),
            ],
        ),
    ]
