# Generated by Django 4.1.5 on 2023-02-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
    ]
