# Generated by Django 4.1.5 on 2023-02-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='re_enter_passwords',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
