# Generated by Django 4.1.5 on 2023-02-15 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service_re_enter_passwords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='re_enter_passwords',
        ),
    ]
