# Generated by Django 4.1.5 on 2023-03-05 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
    ]
