# Generated by Django 4.1.5 on 2023-03-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_remove_products_item_name_remove_products_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='products_names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
