# Generated by Django 4.1.5 on 2023-03-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_products_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_names',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
